version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          working_directory: laravel
      - run: sudo composer self-update --1
      - run:
          name: php test
          command: vendor/bin/phpunit
