version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./laravel/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./laravel
      - save_cache:
          key: composer-v1-{{ checksum "./laravel/composer.lock" }}
          paths:
            - ./laravel/vendor
      - run:
          name: php test
          command: ./laravel/vendor/bin/phpunit --configuration=./laravel/phpunit.xml
